Format shell scripts

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -43,12 +43,12 @@ for i in cmake cmake3; do
     fi
 done
 
-which "${cmake_exe}" > /dev/null 2>&1 || {
+which "${cmake_exe}" >/dev/null 2>&1 || {
     echo "\
 This package requires CMake >= 3, please install it first, then you may
 use this configure script to access CMake equivalent functionality.\
-" >&2;
-    exit 1;
+" >&2
+    exit 1
 }
 
 usage="\
@@ -89,8 +89,8 @@ This typically means that you performed a non-recursive git clone of
 Spicy. To check out the required subdirectories, please execute:
 
   ( cd $source_dir && git submodule update --recursive --init )
-" >&2;
-    exit 1;
+" >&2
+    exit 1
 fi
 
 # Function to append a CMake cache entry definition to the
@@ -98,7 +98,7 @@ fi
 #   $1 is the cache entry variable name
 #   $2 is the cache entry variable type
 #   $3 is the cache entry variable value
-append_cache_entry () {
+append_cache_entry() {
     if [ "$3" != "" ]; then
         cmake_cache_entries="${cmake_cache_entries} -D $1:$2=$3"
     fi
@@ -112,16 +112,16 @@ while [ $# -ne 0 ]; do
     esac
 
     case "$1" in
-        --binary-package)                  cmake_binary_packaging_mode="yes";;
-        --build-dir=*|--builddir=*)        cmake_build_directory="${optarg}";;
-        --build-static-libs)               cmake_build_shared_libs="no";;
-        --build-toolchain=*)               cmake_build_toolchain="${optarg}";;
-        --build-type=*)                    cmake_build_type="${optarg}";;
-        --disable-gold)                    cmake_use_gold="no";;
-        --disable-precompiled-headers)     cmake_use_precompiled_headers="no";;
-        --disable-tests)                   cmake_spicy_enable_tests="no";;
-        --enable-ccache)                   cmake_use_ccache="yes";;
-        --enable-debug)                    cmake_build_type="Debug";;
+        --binary-package) cmake_binary_packaging_mode="yes" ;;
+        --build-dir=* | --builddir=*) cmake_build_directory="${optarg}" ;;
+        --build-static-libs) cmake_build_shared_libs="no" ;;
+        --build-toolchain=*) cmake_build_toolchain="${optarg}" ;;
+        --build-type=*) cmake_build_type="${optarg}" ;;
+        --disable-gold) cmake_use_gold="no" ;;
+        --disable-precompiled-headers) cmake_use_precompiled_headers="no" ;;
+        --disable-tests) cmake_spicy_enable_tests="no" ;;
+        --enable-ccache) cmake_use_ccache="yes" ;;
+        --enable-debug) cmake_build_type="Debug" ;;
         --enable-clang-tidy)
             if ! which clang-tidy >/dev/null 2>&1; then
                 echo "Error: clang-tidy not found in PATH" >&2
@@ -129,58 +129,58 @@ while [ $# -ne 0 ]; do
             fi
 
             cmake_clang_tidy="$(which clang-tidy)"
-        ;;
+            ;;
 
-        --enable-sanitizer)                cmake_use_sanitizers="address";;
-        --enable-sanitizer=*)              cmake_use_sanitizers="${optarg}";;
-        --enable-werror)                   cmake_use_werror="yes";;
-        --generator=*)                     cmake_generator="${optarg}";;
-        --prefix=*)                        cmake_install_prefix="${optarg}";;
-        --with-c-compiler=*)               cmake_c_compiler="${optarg}";;
+        --enable-sanitizer) cmake_use_sanitizers="address" ;;
+        --enable-sanitizer=*) cmake_use_sanitizers="${optarg}" ;;
+        --enable-werror) cmake_use_werror="yes" ;;
+        --generator=*) cmake_generator="${optarg}" ;;
+        --prefix=*) cmake_install_prefix="${optarg}" ;;
+        --with-c-compiler=*) cmake_c_compiler="${optarg}" ;;
         --with-cxx-compiler=*)
             cmake_cxx_compiler="${optarg}"
 
             if [ -z "${cmake_c_compiler}" ]; then
-              try_c_compiler=$(echo "${cmake_cxx_compiler}" | sed 's/++//g')
-              which "${try_c_compiler}" >/dev/null && cmake_c_compiler="${try_c_compiler}"
+                try_c_compiler=$(echo "${cmake_cxx_compiler}" | sed 's/++//g')
+                which "${try_c_compiler}" >/dev/null && cmake_c_compiler="${try_c_compiler}"
             fi
             ;;
 
-        --with-hilti-compiler-launcher=*)  hilti_compiler_launcher="${optarg}";;
+        --with-hilti-compiler-launcher=*) hilti_compiler_launcher="${optarg}" ;;
 
-        --with-clang-tidy=*)               cmake_clang_tidy="${optarg}";;
-        --with-flex=*)                     cmake_flex_root="${optarg}";;
-        --with-bison=*)                    cmake_bison_root="${optarg}";;
-        --without-bison=*)                 cmake_bison_root="";;
-        --without-flex=*)                  cmake_flex_root="";;
+        --with-clang-tidy=*) cmake_clang_tidy="${optarg}" ;;
+        --with-flex=*) cmake_flex_root="${optarg}" ;;
+        --with-bison=*) cmake_bison_root="${optarg}" ;;
+        --without-bison=*) cmake_bison_root="" ;;
+        --without-flex=*) cmake_flex_root="" ;;
 
-        --display-cmake) display_cmake=1;;
+        --display-cmake) display_cmake=1 ;;
 
-        --help|-h) echo "${usage}" 1>&2 && exit 1;;
-        *) echo "Invalid option '$1'.  Try $0 --help to see available options." && exit 1;;
+        --help | -h) echo "${usage}" 1>&2 && exit 1 ;;
+        *) echo "Invalid option '$1'.  Try $0 --help to see available options." && exit 1 ;;
     esac
     shift
 done
 
 # Set CMake cache options.
-append_cache_entry BINARY_PACKAGING_MODE        BOOL   "${cmake_binary_packaging_mode}"
-append_cache_entry BISON_ROOT                   PATH   "${cmake_bison_root}"
-append_cache_entry BUILD_SHARED_LIBS            BOOL   "${cmake_build_shared_libs}"
-append_cache_entry BUILD_TOOLCHAIN              BOOL   "${cmake_build_toolchain}"
-append_cache_entry CMAKE_BUILD_TYPE             STRING "${cmake_build_type}"
-append_cache_entry CMAKE_C_COMPILER             PATH   "${cmake_c_compiler}"
-append_cache_entry CMAKE_CXX_COMPILER           PATH   "${cmake_cxx_compiler}"
-append_cache_entry CMAKE_C_CLANG_TIDY           PATH   "${cmake_clang_tidy}"
-append_cache_entry CMAKE_CXX_CLANG_TIDY         PATH   "${cmake_clang_tidy}"
-append_cache_entry CMAKE_INSTALL_PREFIX         PATH   "${cmake_install_prefix}"
-append_cache_entry HILTI_COMPILER_LAUNCHER      STRING "${hilti_compiler_launcher}"
-append_cache_entry FLEX_ROOT                    PATH   "${cmake_flex_root}"
-append_cache_entry USE_CCACHE                   BOOL   "${cmake_use_ccache}"
-append_cache_entry USE_GOLD                     BOOL   "${cmake_use_gold}"
-append_cache_entry USE_SANITIZERS               STRING "${cmake_use_sanitizers}"
-append_cache_entry HILTI_DEV_PRECOMPILE_HEADERS BOOL   "${cmake_use_precompiled_headers}"
-append_cache_entry USE_WERROR                   BOOL   "${cmake_use_werror}"
-append_cache_entry SPICY_ENABLE_TESTS           BOOL   "${cmake_spicy_enable_tests}"
+append_cache_entry BINARY_PACKAGING_MODE BOOL "${cmake_binary_packaging_mode}"
+append_cache_entry BISON_ROOT PATH "${cmake_bison_root}"
+append_cache_entry BUILD_SHARED_LIBS BOOL "${cmake_build_shared_libs}"
+append_cache_entry BUILD_TOOLCHAIN BOOL "${cmake_build_toolchain}"
+append_cache_entry CMAKE_BUILD_TYPE STRING "${cmake_build_type}"
+append_cache_entry CMAKE_C_COMPILER PATH "${cmake_c_compiler}"
+append_cache_entry CMAKE_CXX_COMPILER PATH "${cmake_cxx_compiler}"
+append_cache_entry CMAKE_C_CLANG_TIDY PATH "${cmake_clang_tidy}"
+append_cache_entry CMAKE_CXX_CLANG_TIDY PATH "${cmake_clang_tidy}"
+append_cache_entry CMAKE_INSTALL_PREFIX PATH "${cmake_install_prefix}"
+append_cache_entry HILTI_COMPILER_LAUNCHER STRING "${hilti_compiler_launcher}"
+append_cache_entry FLEX_ROOT PATH "${cmake_flex_root}"
+append_cache_entry USE_CCACHE BOOL "${cmake_use_ccache}"
+append_cache_entry USE_GOLD BOOL "${cmake_use_gold}"
+append_cache_entry USE_SANITIZERS STRING "${cmake_use_sanitizers}"
+append_cache_entry HILTI_DEV_PRECOMPILE_HEADERS BOOL "${cmake_use_precompiled_headers}"
+append_cache_entry USE_WERROR BOOL "${cmake_use_werror}"
+append_cache_entry SPICY_ENABLE_TESTS BOOL "${cmake_spicy_enable_tests}"
 
 if [ -n "${cmake_generator}" ]; then
     cmake="${cmake_exe} -G '${cmake_generator}' ${cmake_cache_entries} ${source_dir}"
@@ -205,9 +205,9 @@ fi
 
 cd "${cmake_build_directory}"
 fail=$(mktemp)
-{ eval "${cmake}" 2>&1 || echo > "$fail"; } | tee config.log &&  [ ! -s "$fail" ]
+{ eval "${cmake}" 2>&1 || echo >"$fail"; } | tee config.log && [ ! -s "$fail" ]
 rm "$fail"
 
-echo "# This is the command used to configure this build" > config.status
-echo "${command}" >> config.status
+echo "# This is the command used to configure this build" >config.status
+echo "${command}" >>config.status
 chmod u+x config.status
