Switch from checkbashisms.pl to shellcheck
We were previously linting shell scripts with checkbashisms.pl which
implements a subset of functionality already present in shellcheck at
most. It also is a pretty specific tool and editors might more often
come with shellcheck integration instead.

This commit switches us over to checking with shellcheck instead. In
order to make that work we fix issues reported by it, either by
implementing a proper fix or by targetted local suppressions.

diff --git a/ci/run-ci b/ci/run-ci
--- a/ci/run-ci
+++ b/ci/run-ci
@@ -10,24 +10,21 @@
 
 set -o pipefail
 
-name=$(basename $0)
-root=$(cd $(dirname $0)/.. && pwd)
+name=$(basename "$0")
+root=$(cd "$(dirname "$0")"/.. && pwd)
 build=
 install=
 
 jobs=$(nproc)
 
 color_red=$'\e[1;31m'
-color_green=$'\e[1;32m'
 color_yellow=$'\e[1;33m'
-color_blue=$'\e[1;34m'
 color_magenta=$'\e[1;35m'
-color_cyan=$'\e[1;36m'
 color_normal=$'\e[0m'
 
 function usage {
 cat <<EOF
-Usage: ${mame} [<global options>] <stage> [<command options>]
+Usage: ${name} [<global options>] <stage> [<command options>]
 
 Stages
 
@@ -61,29 +58,29 @@ function log_colored {
     color=$1
     shift
     printf "%s" "${color}"
-    printf "%s" "$@"
+    printf "%s" "$*"
     printf "%s\n" "${color_normal}"
 }
 
 function log_stage {
     echo
-    log_colored "${color_magenta}" "### $@"
+    log_colored "${color_magenta}" "### $*"
 }
 
 function log_warning {
-    log_colored "${color_yellow}" "### $@"
+    log_colored "${color_yellow}" "### $*"
 }
 
 function log_error {
-    log_colored "${color_red}" "### $@"
+    log_colored "${color_red}" "### $*"
 }
 
 function log_diag {
-    log_colored "${color_yellow}" "--- $@"
+    log_colored "${color_yellow}" "--- $*"
 }
 
 function error {
-    echo "### Error: $@"
+    echo "### Error: $*"
     exit 1
 }
 
@@ -91,7 +88,7 @@ function run_configure {
     build_type="$1"
     shift
 
-    mkdir -p ${install}
+    mkdir -p "${install}"
     configure="./configure --builddir=${build} --prefix=${install} --generator=Ninja --enable-werror --enable-ccache --with-hilti-compiler-launcher=ccache"
 
     if [ "${build_type}" == "release" ]; then
@@ -113,7 +110,7 @@ function run_configure {
             --clang-tidy)
                 test $# -gt 0 || usage
                 clang_tidy="$2"
-                test -x ${clang_tidy} || error "clang-tidy not found in $2"
+                test -x "${clang_tidy}" || error "clang-tidy not found in $2"
                 shift 2;
                 ;;
 
@@ -141,7 +138,7 @@ function run_configure {
         esac
     done
 
-    if [ -e ${build} ]; then
+    if [ -e "${build}" ]; then
         error "Build directory ${build} already exists, delete first"
     fi
 
@@ -150,9 +147,9 @@ function run_configure {
     log_stage "Running configure ... (${configure})"
 
     ${configure} || exit 1
-    mkdir -p ${artifacts}
+    mkdir -p "${artifacts}"
 
-    echo "${clang_tidy}" >${build}/.clang_tidy
+    echo "${clang_tidy}" >"${build}"/.clang_tidy
 
     if [ -x "${clang_tidy}" ]; then
         pushd "${build}" >/dev/null || exit 1
@@ -167,15 +164,15 @@ function run_build {
     # The level of parallelism chosen here is tuned for what's configured
     # in `.cirrus.yml` so that (1) we align with number of CPUs, and (2) we
     # do not trigger OOM kills in the Docker environments.
-    (cd ${build} && ninja -j "${jobs}" all) || exit 1
+    (cd "${build}" && ninja -j "${jobs}" all) || exit 1
 
     log_stage "Building docs ..."
-    (cd ${root}/doc && make BUILDDIR=${build} DESTDIR=${artifacts}/doc doxygen html) || exit 1
+    (cd "${root}"/doc && make BUILDDIR="${build}" DESTDIR="${artifacts}"/doc doxygen html) || exit 1
 }
 
 function run_install {
     log_stage "Installing code ..."
-    (cd ${build} && ninja install) || exit 1
+    (cd "${build}" && ninja install) || exit 1
 }
 
 function execute_btest {
@@ -196,13 +193,14 @@ function execute_btest {
     fi
 
 
-    log_stage "Running ${name} tests ... (${btest_alternative} ${btest_group})"
-    pushd ${cwd} >/dev/null
+    log_stage "Running ${name} tests ... (${alternative} ${group})"
+    pushd "${cwd}" >/dev/null || exit 1
 
-    eval ${preload} \
+    # shellcheck disable=SC2086
+    eval ${preload:-} \
         btest -j "${jobs}" \
-              -f ${artifacts}/diag.log \
-              -x ${artifacts}/diag.xml \
+              -f "${artifacts}"/diag.log \
+              -x "${artifacts}"/diag.xml \
               -z 3 \
               ${alternative} \
               ${group}
@@ -210,14 +208,14 @@ function execute_btest {
     rc=$?
 
     if [ ${rc} != 0 ]; then
-        cp -a .tmp ${artifacts}/btest-tmp
+        cp -a .tmp "${artifacts}"/btest-tmp
         log_diag "Begin diagnostics"
-        cat ${artifacts}/diag.log
+        cat "${artifacts}"/diag.log
         log_diag "End diagnostics (complete test output in 'btest-tmp')"
         log_error "Tests have failed"
     fi
 
-    popd >/dev/null
+    popd >/dev/null || exit 1
     return ${rc}
 }
 
@@ -257,13 +255,13 @@ function run_test_install {
 
 function run_cleanup {
     log_stage "Cleaning up ..."
-    (cd ${build} && ninja clean) || exit 1
+    (cd "${build}" && ninja clean) || exit 1
     (cd doc && make clean) || exit 1
 }
 
 ### Main
 
-while getopts "r:b:j:" opt; do
+while getopts "r:b:j:h" opt; do
     case "${opt}" in
         h)
             usage
@@ -289,9 +287,9 @@ if [ -z "${build}" ]; then
     build=${root}/build-ci
 fi
 
-install=/tmp/ci-install-$(basename ${build})
-root=$(realpath ${root})
-build=$(realpath ${build})
+install=/tmp/ci-install-$(basename "${build}")
+root=$(realpath "${root}")
+build=$(realpath "${build}")
 artifacts=${build}/ci
 
 cmd=$1
@@ -299,16 +297,16 @@ shift
 
 test -n "${cmd}" || usage
 
-cd ${root}
+cd "${root}" || exit 1
 test -e CMakeLists.txt || error "${root} is not the project's root git repository"
 
 case "${cmd}" in
-    configure)           (run_configure $@);;
-    build)               (run_build $@);;
-    install)             (run_install $@);;
-    test-build)          (run_test_build $@);;
-    test-install)        (run_test_install $@);;
-    test-code)           (run_test_code $@);;
-    cleanup)             (run_cleanup $@);;
+    configure)           (run_configure "$@");;
+    build)               (run_build "$@");;
+    install)             (run_install "$@");;
+    test-build)          (run_test_build "$@");;
+    test-install)        (run_test_install "$@");;
+    test-code)           (run_test_code "$@");;
+    cleanup)             (run_cleanup "$@");;
     *)       usage;;
 esac
