Move protocol analyzers into submodule.
This moves all the protocol analyzers into its own submodule
`spicy-analyzers`, which doubles as a Zeek package installing them.
There's a new `spicy-analyzers` target to pre-compile those analyzers
for Zeek.

Testing works as follows:

  - The Makefile in `tests/` gains a new target `test-analyzers` (plus
    an alias `test-analyzer-build`) that will (1) trigger an analyzer
    build, and then (2) run the analyzer tests.

  - run-ci triggers an explicit "btest" run inside the analyzer
    submodule (same as before).

  - For non-run-ci Cirrus builds that are running tests inside their
    build directory, we add (1) `ninja spicy-analyzers` during the build
    stage, and (2) `make test-analyzers-build` during the testing stage.

  - The top-level Makefile's target change so that `make test` runs
    `test-build` in `tests/`, and `test-all` runs both `test-build` and
    `test-analyzers-build`.

This includes a couple of Zeek plugin changes as well:

  - Move registration of Zeek components to load time.
  - Work around problem in Zeek's analyzer API.

Also updating pathfind to fix problem on Alpine.

diff --git a/ci/run-ci b/ci/run-ci
--- a/ci/run-ci
+++ b/ci/run-ci
@@ -209,6 +209,11 @@ function run_build {
     # do not trigger OOM kills in the Docker environments.
     (cd ${build} && ninja -j4) || exit 1
 
+    if cat ${build}/CMakeCache.txt | egrep -iq 'BUILD_TOOLCHAIN.*(yes|on|off)'; then
+        log_stage "Building analyzers ..."
+        (cd ${build} && ninja -j4 spicy-analyzers) || exit 1
+    fi
+
     log_stage "Building docs ..."
     (cd ${root}/doc && make BUILDDIR=${build} DESTDIR=${artifacts}/doc doxygen html) || exit 1
 
@@ -247,6 +252,33 @@ function run_test_btest {
               -x ${artifacts}/diag.xml \
               ${btest_alternative} \
               ${btest_group}
+
+    rc=$?
+
+    if [ ${rc} != 0 ]; then
+        cp -a .tmp ${artifacts}/btest-tmp
+        log_diag "Begin diagnostics"
+        cat ${artifacts}/diag.log
+        log_diag "End diagnostics (complete test output in 'btest-tmp')"
+        log_error "Tests have failed"
+    fi
+
+    return ${rc}
+}
+
+function run_test_analyzers {
+    export LD_LIBRARY_PATH=$(cat ${build}/.rpath)
+    export ZEEK_LD_PRELOAD=$(cat ${build}/.zeek_ld_preload)
+    export SPICY_MODULE_PATH=${build}/zeek/spicy-analyzers/spicy-modules
+
+    log_stage "Running analyzer tests ..."
+
+    cd zeek/spicy-analyzers/tests
+    eval ${preload} \
+        btest -b \
+              -j 5 \
+              -f ${artifacts}/diag.log \
+              -x ${artifacts}/diag.xml
 
     rc=$?
 
@@ -337,6 +369,10 @@ function run_test_common {
 function run_test_build {
     export SPICY_BUILD_DIRECTORY=${build}
     run_test_common
+
+    pushd $(pwd) >/dev/null
+    run_test_analyzers || rc=1
+    popd >/dev/null
 }
 
 function run_test_install {
